### ISSUE TITLE
the ram addresses in cheat-engine 

### ISSUE THREAD

**Issue by moonair** [sanford1/TapTracker#1]
Cool tool!!
Can the ram addresses use in cheat-engine?
I tried, it seem not working.

**Comment by MaryHal** [comment]
They will not work because they're the emulated RAM addresses, not the addresses for a specific instance of MAME.

May I ask what your intention is?

**Comment by moonair** [comment]
Got it.

I try to write a TAP session tracker in Cheat-engine, finally do it by Mame's cheat.

**Comment by MaryHal** [comment]
I'm curious as to what your "session tracker" is!
"Total time in game" for a play session could be interesting, especially if it's 100% a MAME cheat code.
